In [1]:
pip install requests

Requirement already satisfied: requests in /Users/briannehan/anaconda3/lib/python3.11/site-packages (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/briannehan/anaconda3/lib/python3.11/site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/briannehan/anaconda3/lib/python3.11/site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/briannehan/anaconda3/lib/python3.11/site-packages (from requests) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /Users/briannehan/anaconda3/lib/python3.11/site-packages (from requests) (2023.11.17)
Note: you may need to restart the kernel to use updated packages.

In [12]:
pip install requests pandas geoapify

Requirement already satisfied: requests in /Users/briannehan/anaconda3/lib/python3.11/site-packages (2.31.0)
Requirement already satisfied: pandas in /Users/briannehan/anaconda3/lib/python3.11/site-packages (2.0.3)
ERROR: Could not find a version that satisfies the requirement geoapify (from versions: none)
ERROR: No matching distribution found for geoapify
Note: you may need to restart the kernel to use updated packages.

In [7]:
import os
import csv
import pandas as pd

In [8]:
pb_dens_csv = pd.read_csv('../project-3-brianne/Resources/USGS_polar_bear_maternal_dens_1910-2018.csv')
pb_dens_csv

,Record,DenID,Spring_year,Data_source,Discovery_method,Latitude,Longitude,Confirmation,Substrate,Position_method,Horizontal_error_m
0,384,990,2010,USGS,SATELLITE,69.3637,-143.3672,C,L,Argos LC=3,400
1,385,991,2010,USGS,SATELLITE,70.8224,-153.9907,C,L,Argos LC=3,400
2,386,992,2010,USGS,SATELLITE,70.1321,-145.9387,C,L,Argos LC=3,400
3,387,993,2010,USGS,SATELLITE,70.1787,-145.9717,P,L,Argos LC=3,400
4,388,994,2011,USGS,CONVENTIONAL,70.1952,-146.0769,P,L,field gps,30
...,...,...,...,...,...,...,...,...,...,...,...
71,526,1144,2015,USFWS-ADFG,REPORT,70.2896,-148.5135,P,L,field gps,30
72,527,1145,2015,USFWS-ADFG,FLIR,70.3139,-147.9858,P,L,field gps,30
73,528,1146,2017,USFWS-ADFG,FLIR,70.3153,-147.9995,P,L,field gps,30
74,529,1147,2017,USFWS-ADFG,REPORT,70.3015,-147.8866,C,L,field gps,30
75,530,1148,2018,USFWS-ADFG,REPORT,70.3288,-148.2350,C,L,field gps,30

In [10]:
pb_dens_df = pd.DataFrame(pb_dens_csv)
pb_dens_df

,Record,DenID,Spring_year,Data_source,Discovery_method,Latitude,Longitude,Confirmation,Substrate,Position_method,Horizontal_error_m
0,384,990,2010,USGS,SATELLITE,69.3637,-143.3672,C,L,Argos LC=3,400
1,385,991,2010,USGS,SATELLITE,70.8224,-153.9907,C,L,Argos LC=3,400
2,386,992,2010,USGS,SATELLITE,70.1321,-145.9387,C,L,Argos LC=3,400
3,387,993,2010,USGS,SATELLITE,70.1787,-145.9717,P,L,Argos LC=3,400
4,388,994,2011,USGS,CONVENTIONAL,70.1952,-146.0769,P,L,field gps,30
...,...,...,...,...,...,...,...,...,...,...,...
71,526,1144,2015,USFWS-ADFG,REPORT,70.2896,-148.5135,P,L,field gps,30
72,527,1145,2015,USFWS-ADFG,FLIR,70.3139,-147.9858,P,L,field gps,30
73,528,1146,2017,USFWS-ADFG,FLIR,70.3153,-147.9995,P,L,field gps,30
74,529,1147,2017,USFWS-ADFG,REPORT,70.3015,-147.8866,C,L,field gps,30
75,530,1148,2018,USFWS-ADFG,REPORT,70.3288,-148.2350,C,L,field gps,30

In [17]:
def get_zipcode(latitude, longitude, api_key):
    # Define the get_zipcode function as shown in the previous example...

# Load your data from the DataFrame (replace 'df' and column names accordingly)
    pb_dens_df = pd.read_csv('../project-3-brianne/Resources/USGS_polar_bear_maternal_dens_1910-2018.csv')  # Replace with your data source
api_key = 'eab569d164134e24bd999800c17395d3'

# Create an empty list to store the ZIP codes
zipcodes = []

# Loop through the DataFrame rows and get ZIP codes
for index, row in pb_dens_df.iterrows():
    latitude = row['Latitude']  # Replace 'Latitude' with your latitude column name
    longitude = row['Longitude']  # Replace 'Longitude' with your longitude column name
    
    # Get the ZIP code for the current coordinates
    zipcode = get_zipcode(latitude, longitude, api_key)

    # Append the ZIP code to the list
    zipcodes.append(zipcode)

# Add the list of ZIP codes to the DataFrame
pb_dens_df['ZIP Code'] = zipcodes

# Save the DataFrame with ZIP codes to a new CSV file (optional)
pb_dens_df.to_csv('data_with_zipcodes.csv', index=False)

In [18]:
pb_dens_df

,Record,DenID,Spring_year,Data_source,Discovery_method,Latitude,Longitude,Confirmation,Substrate,Position_method,Horizontal_error_m,ZIP Code
0,384,990,2010,USGS,SATELLITE,69.3637,-143.3672,C,L,Argos LC=3,400,None
1,385,991,2010,USGS,SATELLITE,70.8224,-153.9907,C,L,Argos LC=3,400,None
2,386,992,2010,USGS,SATELLITE,70.1321,-145.9387,C,L,Argos LC=3,400,None
3,387,993,2010,USGS,SATELLITE,70.1787,-145.9717,P,L,Argos LC=3,400,None
4,388,994,2011,USGS,CONVENTIONAL,70.1952,-146.0769,P,L,field gps,30,None
...,...,...,...,...,...,...,...,...,...,...,...,...
71,526,1144,2015,USFWS-ADFG,REPORT,70.2896,-148.5135,P,L,field gps,30,None
72,527,1145,2015,USFWS-ADFG,FLIR,70.3139,-147.9858,P,L,field gps,30,None
73,528,1146,2017,USFWS-ADFG,FLIR,70.3153,-147.9995,P,L,field gps,30,None
74,529,1147,2017,USFWS-ADFG,REPORT,70.3015,-147.8866,C,L,field gps,30,None
75,530,1148,2018,USFWS-ADFG,REPORT,70.3288,-148.2350,C,L,field gps,30,None

In [11]:
lat_long = pb_dens_df[['Latitude', 'Longitude']]
lat_long

    Latitude  Longitude
0    69.3637  -143.3672
1    70.8224  -153.9907
2    70.1321  -145.9387
3    70.1787  -145.9717
4    70.1952  -146.0769
..       ...        ...
71   70.2896  -148.5135
72   70.3139  -147.9858
73   70.3153  -147.9995
74   70.3015  -147.8866
75   70.3288  -148.2350

[76 rows x 2 columns]

In [4]:
import requests

def get_zipcode(latitude, longitude, api_key):
    base_url = "https://api.geoapify.com/v1/geocode/reverse"
    params = {
        "lat": latitude,
        "lon": longitude,
        "apiKey": api_key
    }

    try:
        response = requests.get(base_url, params=params)
        data = response.json()
        
        if "features" in data and len(data["features"]) > 0:
            properties = data["features"][0]["properties"]
            if "postcode" in properties:
                return properties["postcode"]
            elif "postalCode" in properties:
                return properties["postalCode"]

        return None  # ZIP code not found in the response

    except Exception as e:
        print(f"Error: {str(e)}")
        return None

# Example coordinates (replace with your own)
latitude = 70.8224
longitude = -153.9907
api_key = 'eab569d164134e24bd999800c17395d3'

# Get the ZIP code
zipcode = get_zipcode(latitude, longitude, api_key)
if zipcode:
    print(f"ZIP code: {zipcode}")
else:
    print("ZIP code not found.")

ZIP code not found.

In [19]:
import csv
import json

# Define the function to convert CSV to JSON
def csv_to_json(csv_file, json_file):
    data = []
    with open(csv_file, mode='r') as csv_file:
        csv_reader = csv.DictReader(csv_file)
        for row in csv_reader:
            data.append(row)

    with open(json_file, mode='w') as json_file:
        json.dump(data, json_file, indent=4)

# Specify the file paths (replace with your own)
csv_file_path = '../project-3-brianne/Resources/USGS_polar_bear_maternal_dens_1910-2018.csv'  # Replace with your CSV file path
json_file_path = '../project-3-brianne/Resources/USGS_polar_bear_maternal_dens_1910-2018.json'  # Replace with your desired JSON file path

# Call the function to convert CSV to JSON
csv_to_json(csv_file_path, json_file_path)

In [28]:
# Define the function to convert CSV to JSON
def csv_to_json(csv_file, json_file):
    data = []
    with open(csv_file, mode='r') as csv_file:
        csv_reader = csv.DictReader(csv_file)
        for row in csv_reader:
            data.append(row)

    with open(json_file, mode='w') as json_file:
        json.dump(data, json_file, indent=4)

# Specify the file paths (replace with your own)
csv_file_path = '../project-3-brianne/Resources/2018_pb_dens.csv'  # Replace with your CSV file path
json_file_path = '../project-3-brianne/Resources/2018_pb_dens.json'  # Replace with your desired JSON file path

# Call the function to convert CSV to JSON
csv_to_json(csv_file_path, json_file_path)